### ISSUE TITLE
Create seeds

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentDeTerrassa/decidim-terrassa#3]
Seeds for this app should include:

* An organitzation with the right logo

**Comment by mrcasals** [comment]
Will need the right logo for this, then

**Comment by josepjaume** [comment]
Hmmm just create the org then, we'll add the logo later.

**Comment by mrcasals** [comment]
Done, see http://decidim-terrassa.herokuapp.com

**Comment by mrcasals** [comment]
Reopening this issue since it's not really fixed (I misunderstood the purpose of this issue).

We need to create an organization in the `db/seeds.rb` file, so that this is the one used by all seeds.  This organization needs to have:

- The correct name ("Decidim Terrassa")
- The correct logos
- The correct host (localhost or the Review App one)
- The correct locales (Catalan and Spanish)

**Comment by josepjaume** [comment]
Appending the "official" logos.

![escut-terrassa-big](https://cloud.githubusercontent.com/assets/111746/24146428/fc5bc434-0e35-11e7-9976-a7ba2a05525b.png)
![logo-terrassa-big](https://cloud.githubusercontent.com/assets/111746/24146429/fc761aaa-0e35-11e7-8b58-296bc9da33b6.png)
